join:
  broadcast:
    player-welcome: "欢迎新人：%playername% 加入游戏~"
    player-join: "%playername% 重返游戏!"
  dispatch:
    notices:
      # add ' - ' mean this key-value map type
      - "服务器社区 -> https://kaihei.co/HIHPPK  <- 点击进入"
    commands:
      - "/sps [show|hide] 显示或关闭排行榜插件"

quit:
  broadcast:
    player-quit: "%playername% 退出游戏..."

motd:
  enabled: true
  display:
    main:
      - "&b&l&m-----------[&r&6&l 进来挨骂! &b&l&m]-----------&r"
    intro:
      - "&r&e&l交流社区: &f https://kaihei.co/qH2400 "
      - "&r&a在?  来点 &8&l矿工 &a!!! "