join:
  broadcast:
    player-welcome: "欢迎新人：%playername% 加入游戏~"
    player-join: "%playername% 重返游戏!"
    player-quit: "%playername% 退出游戏..."
  dispatch:
    notices:
      # add ' - ' mean this key-value map type
      - kaihei: "服务器社区 -> https://kaihei.co/HIHPPK  <- 点击进入"
    commands:
      - sps: "/sps < show | hide > 显示或关闭排行榜插件"
