main: cc.squirtle.GamePrompt.App
name: GamePrompt
version: 0.1
author: squirtlecc

# Replace "test" with the name of your command.
commands:
  gameprompt:
    aliases: [sgp,gmotd]
    description: setting your server prompt when player in your server
    usage: |
      Use /help <command> to get more information about this plugins
      - /<command> [dm|deathmsg] - get last death message
      - /<command> list - list all gameprompt in game
      - /<command> set - setting gameprompt in game
    # permission: yourplugin.yourcommandpermission